name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to Cafe24 via SFTP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cafe24_key
          chmod 600 ~/.ssh/cafe24_key
          ssh-keyscan -H ${{ secrets.FTP_HOST }} >> ~/.ssh/known_hosts
          
          echo "=== Testing SFTP connection ==="
          echo "pwd
          ls -la
          bye" > /tmp/test_sftp.txt
          
          sftp -b /tmp/test_sftp.txt \
            -i ~/.ssh/cafe24_key \
            -P 22 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}
          
          echo "=== SFTP test completed ==="
